# Generated by Django 4.2.3 on 2023-07-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aluguel", "0002_address_client_theme_rent_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="rent",
            name="price",
            field=models.FloatField(default=0.0),
        ),
    ]
